// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkkbunzkqnxoqgjraiey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdra2J1bnprcW54b3FnanJhaWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5ODMzMzEsImV4cCI6MjA1NTU1OTMzMX0.UeL7AGcfZazjCiakaxEsSSuv4KN9pffmNMCnRJUYPIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);